### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by soerface**
Add a license to the project. Otherwise, default copyright laws apply and [no one may reproduce, distribute, or create derivative works from this work](https://help.github.com/articles/licensing-a-repository/)

@tiansh @ansvonwa @malled2002 @landfillbaby I need your approval, is the MIT license ok for your previous work?

### CODE REVIEW

**Comment by tiansh** [comment]
I felt OK for MIT and even for CC 0.

**Comment by ansvonwa** [comment]
MIT is okay for me :ok_hand:

**Comment by landfillbaby** [comment]
yeah i'm fine with MIT

**Comment by malled2002** [comment]
MIT is ok

**Comment by landfillbaby** [comment]
i think you should delete the license branch since it's merged

**Pull request merged**
