### PR TITLE
my solutions

### PR DESCRIPTION
**Pull request by landfillbaby**
currently up to level 34
i took the liberty of overwriting solutions i improved or beat

### CODE REVIEW

**Comment by landfillbaby** [comment]
it might be failing because i have travis building on my end too, i don't know

**Comment by soerface** [comment]
@landfillbaby thanks! It is failing because Travis CI isn't exposing my GitHub Key to Pull Requests, leading to failures because of GitHubs rate limit (I'm using the API for the avatars and name). But I'm using it anyway just to build the GitHub Pages site, so no problem that it is failing. I'll reconfigure Travis sometime else, don't worry.

My checklist for reviewing, will merge when I looked into all of them:
* [ ] 6
* [ ] 7
* [ ] 10
* [ ] 12
* [ ] 13
* [ ] 15
* [ ] 16
* [ ] 18
* [ ] 19
* [ ] 22
* [ ] 23
* [ ] 24
* [ ] 25
* [ ] 26
* [ ] 30
* [ ] 32
* [ ] 34

**Comment by landfillbaby** [comment]
i did a few more solutions yesterday
you can change my master branch directly if you want

**Comment by soerface** [comment]
"Merging is blocked" is also my mistake, I failed to enable commit signing on all of my computers. Don't worry.

I will review the solutions you gave my initially. I'm not able to keep up if you are keep adding solutions. Also, I will change the `add_solutions.py` script to not remove existing solutions, @ansvonwa and me are planning to keep more solutions.

**Comment by soerface** [comment]
I've reviewed and merged everyting to year 34. May you open a new pull request for the remaining ones? I've changed the `add_solution.py` script so it won't remove other solutions.

**Pull request closed without merging**
